fail_fast: true

repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: bash scripts/lint.sh
        language: system
        files: ^src/merchant/|^tests/|^examples/
        types: [file, python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: docstringcheck
        name: docstringcheck
        entry: bash scripts/docstring.sh
        language: system
        files: ^src/merchant/
        types: [file, python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash scripts/test-coverage-xml.sh unit
        language: system
        files: ^src/merchant/|^tests/
        types: [file, python]
        pass_filenames: false
