repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        stages: [push]
        args: ["--check-only", "--diff", "--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
        stages: [push]
        args: ["--check", "--diff", "--color"]
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        stages: [push]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        stages: [push]
        args: [--show-error-codes]
        additional_dependencies: ['types-requests']
  - repo: local
    hooks:
      - id: pytest
        name: run unit tests
        entry: pytest --suppress-no-test-exit-code
        language: system
        types: [python]
        stages: [push]
        pass_filenames: false
