
version: "3.8"
services:
    minio:
        image: minio/minio:latest
        restart: unless-stopped
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
            MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 30s
            timeout: 20s
            retries: 3
        command: server --console-address ":9001" /data/
        volumes: 
            - ./Storage/minio_storage:/data

    redis:
        image: redis
        restart: unless-stopped

    mlflow-db:
        image: postgres:13
        restart: unless-stopped
        environment:
            POSTGRES_USER=: ${POSTGRES_USER}
            POSTGRES_PASSWORD=: ${POSTGRES_PASSWORD}
            POSTGRES_DB: mlflow_backend_store_db
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
        - ./storage/mlflow_data:/var/lib/postgresql/data/pgdata

    airflow-db:
        image: postgres:13
        restart: unless-stopped
        environment:
            POSTGRES_USER=: ${POSTGRES_USER}
            POSTGRES_PASSWORD=: ${POSTGRES_PASSWORD}
            POSTGRES_DB: airflow_backend_store_db
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
        - ./storage/airflow_data:/var/lib/postgresql/data/pgdata
        ports:
        - "5433:5432"

    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
        - ./storage/pgadmin_data/:/var/lib/pgadmin
        ports:
        - "5050:80"